.TH DEBDELTA "1" "aug 2009" "debdelta" "User Commands"

.SH NAME 

debdelta \- compute changes between Debian packages

.SH SYNOPSIS

.B debdelta 
[\fIOPTION\fR]... \fIFROMFILE\fR \fITOFILE\fR \fIDELTA
.SH DESCRIPTION

This program computes changes between Debian packages FROMFILE and
TOFILE. These changes are stored in the file DELTA.  The DELTA
file may later be used by the "debpatch" program to recreate TOFILE
from FROMFILE. In a sense, the pair of programs "debdelta"/"debpatch"
operate on Debian packages similar to how the pair "diff"/"patch"
operate on text files; indeed, the output of "debdelta" may be used to
store and transmit only the changes between Debian packages; but,
contrary to the "diff" output, the output of "debdelta" is not human
readable, but rather it is intended to be as small as possible (to
optimize for less disk usage and/or faster transmission).

.SH OPTIONS

.TP
\fB\-\-signing\-key\fR \fIKEY\fR
key used to sign the delta (using GnuPG).
.TP
\fB\-\-no\-md5\fR
do not include MD5 info in delta.
.TP
\fB\-\-needsold\fR
create a patch that can only be used if the old .deb is available.
.TP
\fB\-\-delta-algo\fR \fIALGO\fR
use a specific backend for computing
binary diffs; possible values are: xdelta xdelta-bzip xdelta3 bsdiff
.TP
\fB\-M \fIMb\fR
maximum memory  to use (for 'bsdiff' or 'xdelta').
.TP
\fB\-v\fR
verbose (can be added multiple times).
.TP
\fB\-d\fR
print full traceback on Python errors; save useful info in temporary files 
in case that a backend crashes.

(If '-d' is added multiple times, it also adds to the patches other
extra debugging checks: only for advanced bug tracking).
.TP
\fB\-k\fR
keep temporary files (use for debugging).
.TP
.BI \--gpg-home 
specify a different home for GnuPG,
default for root is
.I /etc/debdelta/gnupg
while for other users is unset. See 
.I --homedir
in 
.BR gpg(1)
for details.
.TP
.BI \--disable-feature  \ FEATURE
disable an internal feature. See the documentation in README.features.

.SH "EXAMPLE"

The command
.br
.I debdelta  libglib_2.12_all.deb libglib_2.14_all.deb /tmp/glib.debdelta
.br 
will express the difference between two versions of libglib
in /tmp/glib.debdelta ; the command
.br
.I debpatch \-A /tmp/glib.debdelta libglib_2.12_all.deb /tmp/glib.deb
.br
will create in /tmp/glib.deb a perfect copy of libglib_2.14_all.deb.

.SH SECURITY

A Debian package that is recreated using debpatch is byte-by-byte
identical to the original one; so the cryptographic
archive authentication support for APT (see 
.BR apt-secure (8)
) may be used to assert that it can be trusted to be
installed. Moreover, if  a GnuPG key is specified using
.BI \--signing-key
then the delta file itself is cryptograhically protected using GnuPG, MD5
and SHA1  (using the same method as
.BR dpkg-sig (1)
).
Note that, for non-root users,  the master debdelta keyring 
.I /usr/share/keyrings/debian-debdelta-archive-keyring.gpg
is added to the list of keyrings for gnupg.

.SH EXIT STATUS
.TP
0
if OK,
.TP
1
if there was a retriable problem (e.g., out-of-disk-space,
or an auxiliary program such 'lzma' is missing
and the user is asked to install the package 'lzma'),
.TP
2
if there was a non-retriable problem,
.TP
3
if there was an error in a  command\-line option, or in a configuration file,
.TP
4
if there is an internal error, and
.TP
5
if exited due to keyboard interrupt.

.SH "REPORTING BUGS"

Report bugs to <mennucc1@debian.org>.
.SH AUTHORS

Debdelta was written and is copyright \(co 2006-09 Andrea Mennucci.
.br
This man page was written by Jegou Pierre-yves  <pierreyves.jeg@voila.fr>.

.SH COPYING

This is free software.  You may redistribute copies of it under the terms of
the GNU Library General Public License 
<http://www.gnu.org/licenses/lgpl-2.0.html>.
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"

.BR debdelta-upgrade (1),
.BR debpatch (1),
.BR debdeltas (1),
.BR /usr/share/doc/debdelta/README.
