.TH DEBDELTAS "1" "aug 2009" "debdeltas" "User Commands"
.SH NAME 

debdeltas \- compute changes between Debian packages

.SH SYNOPSIS

.B debdeltas 
[\fIOPTION\fR]... \fIFILES\fR ....

.SH DESCRIPTION

This program computes changes between many Debian packages FILES;
FILES are grouped by package name and architecture; 
for each group, N deltas are computed (see "-n" option);
these are stored in many delta file; the location of
the delta files is specified by the "--dir" option.

.SH OPTIONS
.TP
\fB\-\-dir \fIDIR
force saving of deltas in this DIR
(otherwise they go in the dir of the newer deb_file)
.TP
\fB\-\-alt \fIDIR
for any cmdline argument, search for debs also in this dir
.TP
In the above two options, if DIR ends in // , then the dirname
of the cmdline argument will be appended to DIR, as well; this is
useful when creating archives, since it can recreate the
directory tree.
.TP
.B --signing-key \fI KEY
key used to sign the deltas (using GnuPG)
.TP
\fB\-n \fIN
how many deltas to produce for each unique package name (default 1)
.TP
.B --clean-deltas
delete deltas if newer deb is not in archive
.TP
.B --clean-alt
delete debs in --alt if too old (see -n )
.TP
\fB\-\-no\-md5
do not include MD5 info in debdelta.
.TP
\fB\-\-needsold\fR
create a patch that can only be used if the old .deb is available.
.TP
\fB\-\-delta-algo\fR \fIALGO
use a specific backend for computing
binary diffs; possible values are: xdelta xdelta-bzip xdelta3 bsdiff
.TP
\fB\-M \fIMb
maximum memory  to use (for 'bsdiff' or 'xdelta').
.TP
\fB\--test
check that the patch does apply.
.TP
\fB\-v
verbose (can be added multiple times).
.TP
\fB\-d
print traceback on errors; save useful info in temporary files 
in case that a backend crashes.

(If '-d' is added multiple times, it also adds to the patches other
extra debugging checks: only for advanced bug tracking).
.TP
\fB\-k
keep temporary files (use for debugging).
.TP
.B --gpg-home 
specify a different home for GnuPG,
default for root is
.I /etc/debdelta/gnupg
while for other users is unset. See 
.I --homedir
in 
.BR gpg(1)
for details.
.TP
.BI \--disable-feature  \ FEATURE
disable an internal feature. See the documentation in README.features.

.SH SECURITY

See 
.BR debdelta (1)

.SH EXIT STATUS

See 
.BR debdelta (1)

.SH "REPORTING BUGS"

Report bugs to <mennucc1@debian.org>.

.SH AUTHORS

Debdelta was written and is copyright \(co 2006-09 Andrea Mennucci.
.br
This man page was written by Jegou Pierre-yves  <pierreyves.jeg@voila.fr>.

.SH COPYING

This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"

.BR debpatch (1),
.BR debdelta (1),
.BR /usr/share/doc/debdelta/README .
